# StatsBomb360

## a. Events data

In [12]:
import pandas as pd
import json

with open('../data/statsbomb360/events/3788747.json', 'r') as f:
    data = json.load(f)
    events_df = pd.json_normalize(data)


# See pandas documentation for more details and methods to use
events_df.head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,foul_committed.card.name,pass.outswinging,substitution.outcome.id,substitution.outcome.name,substitution.replacement.id,substitution.replacement.name,50_50.outcome.id,50_50.outcome.name,ball_recovery.offensive,goalkeeper.success_in_play
0,44c21046-f100-45a8-9ebd-62e6ea566fc6,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,64f6e285-4283-437a-94b7-b3fa709a80e5,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c40a128a-fd7d-4424-bd24-1854d6d65242,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11e6946d-1083-4324-a4b8-36a8f3ebd4d3,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ac1dfe29-900f-4799-8686-77e4936d535c,5,1,00:00:01.458,0,1,2,0.720508,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## b. Line-ups data

In [11]:
import pandas as pd
import json

with open('../data/statsbomb360/lineups/3788747.json', 'r') as f:
    lineups = json.load(f)

lineups_df = pd.json_normalize(lineups, record_path=[['lineup']])
lineups_df

,player_id,player_name,player_nickname,jersey_number,cards,positions,country.id,country.name
0,3325,Marko ArnautoviÄ‡,None,7,[],"[{'position_id': 22, 'position': 'Right Center...",15,Austria
1,3969,Aleksandar DragoviÄ‡,None,3,[],"[{'position_id': 3, 'position': 'Right Center ...",15,Austria
2,8220,David Olatukunbo Alaba,David Alaba,8,[],"[{'position_id': 4, 'position': 'Center Back',...",15,Austria
3,8307,Martin Hinteregger,None,4,[],"[{'position_id': 5, 'position': 'Left Center B...",15,Austria
4,8309,Michael Gregoritsch,None,11,[],"[{'position_id': 24, 'position': 'Left Center ...",15,Austria
5,8506,Konrad Laimer,None,24,[],"[{'position_id': 13, 'position': 'Right Center...",15,Austria
6,8513,Stefan Ilsanker,None,6,[],"[{'position_id': 10, 'position': 'Center Defen...",15,Austria
7,8518,Marcel Sabitzer,None,9,[],"[{'position_id': 15, 'position': 'Left Center ...",15,Austria
8,8768,Alexander Schlager,None,1,[],[],15,Austria
9,8769,Xaver Schlager,None,23,[],"[{'position_id': 10, 'position': 'Center Defen...",15,Austria
10,8777,Andreas Ulmer,None,2,[],"[{'position_id': 8, 'position': 'Left Wing Bac...",15,Austria
11,8779,Stefan Lainer,None,21,"[{'time': '84:12', 'card_type': 'Yellow Card',...","[{'position_id': 7, 'position': 'Right Wing Ba...",15,Austria
12,8931,Philipp Lienhart,None,15,[],"[{'position_id': 3, 'position': 'Right Center ...",15,Austria
13,9086,Louis Schaub,None,17,[],[],15,Austria
14,9164,Christopher Trimmel,None,16,[],[],15,Austria
15,11280,Valentino Lazaro,None,22,[],[],15,Austria
16,11281,Alessandro SchÃ¶pf,None,18,[],[],15,Austria
17,11396,Florian Grillitsch,None,10,[],[],15,Austria
18,13309,Pavao Pervan,None,12,[],[],15,Austria
19,18762,Sasa Kalajdzic,None,25,[],"[{'position_id': 22, 'position': 'Right Center...",15,Austria
20,20037,Julian Baumgartlinger,None,14,[],"[{'position_id': 13, 'position': 'Right Center...",15,Austria
21,21532,Daniel Bachmann,None,13,[],"[{'position_id': 1, 'position': 'Goalkeeper', ...",15,Austria
22,24977,Christoph Baumgartner,None,19,[],"[{'position_id': 24, 'position': 'Left Center ...",15,Austria
23,4713,Ezgjan Alioski,None,8,"[{'time': '51:14', 'card_type': 'Yellow Card',...","[{'position_id': 8, 'position': 'Left Wing Bac...",135,"Macedonia, Republic of"
24,6782,Enis Bardhi,None,17,[],"[{'position_id': 13, 'position': 'Right Center...",135,"Macedonia, Republic of"
25,7146,Goran Pandev,None,10,[],"[{'position_id': 22, 'position': 'Right Center...",135,"Macedonia, Republic of"
26,10592,Stefan Ristovski,None,13,[],"[{'position_id': 3, 'position': 'Right Center ...",135,"Macedonia, Republic of"
27,16535,Eljif Elmas,None,21,[],"[{'position_id': 15, 'position': 'Left Center ...",135,"Macedonia, Republic of"
28,16629,Ivan Trichkovski,Ivan Trickovski,7,[],"[{'position_id': 15, 'position': 'Left Center ...",135,"Macedonia, Republic of"
29,16740,Boban Nikolov,None,16,[],"[{'position_id': 7, 'position': 'Right Wing Ba...",135,"Macedonia, Republic of"
30,18879,Arijan Ademi,None,5,[],"[{'position_id': 10, 'position': 'Center Defen...",135,"Macedonia, Republic of"
31,21397,Stole Dimitrievski,None,1,[],"[{'position_id': 1, 'position': 'Goalkeeper', ...",135,"Macedonia, Republic of"
32,30322,Darko Churlinov,None,25,[],[],135,"Macedonia, Republic of"
33,30512,Aleksandar Trajkovski,None,9,"[{'time': '41:26', 'card_type': 'Yellow Card',...","[{'position_id': 24, 'position': 'Left Center ...",135,"Macedonia, Republic of"
34,30644,Darko Velkovski,None,14,[],"[{'position_id': 4, 'position': 'Center Back',...",135,"Macedonia, Republic of"
35,41836,Ferhan Hasani,None,11,[],[],135,"Macedonia, Republic of"
36,44229,Tihomir Kostadinov,None,15,[],"[{'position_id': 24, 'position': 'Left Center ...",135,"Macedonia, Republic of"
37,44962,Milan Ristovski,None,26,[],"[{'position_id': 5, 'position': 'Left Center B...",135,"Macedonia, Republic of"
38,46906,Visar Musliu,None,6,[],"[{'position_id': 5, 'position': 'Left Center B...",135,"Macedonia, Republic of"
39,46908,Damjan Shishkovski,Damjan Siskovski,22,[],[],135,"Macedonia, Republic of"
40,46909,Stefan Spirovski,None,20,[],[],135,"Macedonia, Republic of"
41,46910,Kire Ristevski,None,4,[],[],135,"Macedonia, Republic of"
42,46913,Krste Velkoski,None,19,[],[],135,"Macedonia, Republic of"
43,46915,Egzon Bejtulai,None,2,[],"[{'position_id': 7, 'position': 'Right Wing Ba...",135,"Macedonia, Republic of"
44,73852,Daniel Avramovski,None,24,[],[],135,"Macedonia, Republic of"
45,102733,Risto Jankov,None,12,[],[],135,"Macedonia, Republic of"

## c. Three-Sixty data

In [19]:
import pandas as pd
import json

path = '../data/statsbomb360/three-sixty/3788747.json'

with open(path, 'r') as f:
    data = json.load(f)

freeze_frame = pd.json_normalize(data, record_path=[['freeze_frame']])
visible_area = pd.json_normalize(data, record_path=[['visible_area']])
df_raw = pd.read_json(path)
df_raw, freeze_frame, visible_area

(                                event_uuid  ...                                       freeze_frame
 0     ac1dfe29-900f-4799-8686-77e4936d535c  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 1     ad8b0a8f-e363-4d19-9dfd-45983f94f7b1  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 2     9c6749b1-e39c-493d-bcdb-bee7b6ec4291  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 3     f37b43e4-3abc-4fd5-b823-e5b4df3f5964  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 4     b5dcf0b1-dbc1-457a-a0ca-b34af137a60b  ...  [{'teammate': True, 'actor': True, 'keeper': F...
 ...                                    ...  ...                                                ...
 3092  e7a8d185-f116-4644-9a87-5d1d7ac03dea  ...  [{'teammate': True, 'actor': True, 'keeper': T...
 3093  5b583d5a-37ff-4824-a36c-b180df7c4b1e  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 3094  f82ab3df-9c04-4ee8-a147-6865b6fd725f  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 3095  5b2b9a01-5e0e-4993-838c-0e3d2c6652b3  ...  [{'teammate': True, 'actor': False, 'keeper': ...
 3096  b72c67bb-1298-4385-aa41-c0c1cb7bb61a  ...  [{'teammate': True, 'actor': False, 'keeper': ...

 [3097 rows x 3 columns],
       teammate  actor  keeper                location
 0         True  False   False     [37.03228, 39.2032]
 1         True  False   False  [39.757694, 20.032225]
 2         True  False   False  [41.324688, 52.284233]
 3         True  False   False   [49.25518, 43.547577]
 4         True  False   False   [50.712784, 36.29751]
 ...        ...    ...     ...                     ...
 44223     True   True   False    [53.98201, 43.32913]
 44224     True  False   False  [55.515015, 14.705797]
 44225    False  False   False   [59.073296, 54.00895]
 44226    False  False   False   [59.200123, 46.23969]
 44227    False  False   False  [59.869995, 29.436926]

 [44228 rows x 4 columns],
                 0
 0      102.789671
 1        0.000000
 2       76.931276
 3       77.430828
 4       42.521873
 ...           ...
 36063   70.331935
 36064    9.635870
 36065    0.000000
 36066   65.985036
 36067    0.000000

 [36068 rows x 1 columns])

# Tracab data

In [6]:
import pandas as pd

df = pd.read_parquet('../data/tracab/Group Stage/Austria v North Macedonia/frames.parquet')

# You can use df, which is a Pandas DataFrame to do any visualization you want
df.head()

,time,ball_type,ball_id,ball_x,ball_y,ball_z,ball_sampling,player1_type,player1_id,player1_x,...,player21_type,player21_id,player21_x,player21_y,player21_sampling,player22_type,player22_id,player22_x,player22_y,player22_sampling
0,2021-06-13T15:59:51.493Z,7,0,-5550,-651,50,0,0,1909713,-1663,...,0,250089289,31,18,2,0,250024349,-758,395,2
1,2021-06-13T15:59:51.533Z,7,0,-5550,-651,50,0,0,1909713,-1663,...,0,250089289,31,18,0,0,250024349,-758,394,0
2,2021-06-13T15:59:51.573Z,7,0,-5550,-651,50,0,0,1909713,-1663,...,0,250089289,30,18,0,0,250024349,-758,394,0
3,2021-06-13T15:59:51.613Z,7,0,-5550,-651,50,0,0,1909713,-1663,...,0,250089289,31,18,0,0,250024349,-758,394,0
4,2021-06-13T15:59:51.653Z,7,0,-5550,-651,50,0,0,1909713,-1663,...,0,250089289,31,18,0,0,250024349,-758,394,0

# Wyscout

See [this snippet](https://gitlab.ethz.ch/socceranalytics/uefa-euro-2020/-/snippets/428)

In [3]:
import sys
sys.path.append("..")

from helpers.helper import unzip_bz2

unzip_bz2('../../data/tracab/Group Stage/Austria v North Macedonia/Austria v North Macedonia.xml.bz2', '../../data/tracab/Group Stage/Austria v North Macedonia/Austria v North Macedonia.xml')

Unzippped '../../data/tracab/Group Stage/Austria v North Macedonia/Austria v North Macedonia.xml.bz2' to '../../data/tracab/Group Stage/Austria v North Macedonia/Austria v North Macedonia.xml'